FROM scratch AS stage1

ADD alpine-minirootfs-3.21.3-aarch64.tar.gz /

RUN apk add --no-cache go

ARG VERSION="1.0.0"
ENV VERSION=${VERSION}

WORKDIR /src
COPY main.go .
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o /server main.go

FROM nginx:alpine

ARG VERSION="1.0.0"
ENV VERSION=${VERSION}

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=stage1 /server /app/server

RUN echo '#!/bin/sh' > /docker-entrypoint.d/99-start-go.sh && \
  echo '/app/server &' >> /docker-entrypoint.d/99-start-go.sh && \
  chmod +x /docker-entrypoint.d/99-start-go.sh

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD curl -f http://localhost:8080/ || exit 1

EXPOSE 80
